linters:
  enable-all: true
  fast: true
  disable:
    - godot
    - dupl
    - gofumpt
    - gci
    - testpackage
    - gocyclo # blocked by the giant to string methof of token kind
    - cyclop # blocked by the giant to string methof of token kind
    - funlen # blocked by the giant to string methof of token kind
linters-settings:
  interfacebloat:
    max: 18
  depguard:
    rules:
      prevent_unmaintained_packages:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - swahili
          - github.com/sanity-io/litter
          - github.com/spf13/cobra
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
