version: 2

project_name: swa

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy
   # - ./test.sh

checksum:
  name_template: "checksums.txt"

docker_digest:
  name_template: "digests.txt"

builds:
  - env:
      - CGO_ENABLED=1
    flags:
      - -buildvcs=false
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - maintainer: Pape Pathe <pathe.sene@gmail.com>
    description: Swa Programming Language Compiler
    homepage: https://github.com/PapePathe/swa
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - clang-19
      - lld-19

brews:
  - name: swa
    repository:
      owner: PapePathe
      name: homebrew-swa
    homepage: https://github.com/PapePathe/swa
    description: Swa Programming Language Compiler
    install: |
      bin.install "swa"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  mode: keep-existing
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
