name: Go
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/papepathe/swa-base-container-builder:master
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: lang
        run: go build -v -o ../tests/swa
      - name: Test
        working-directory: lang
        run: go test -v -coverprofile=coverage.txt ./...
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.0
        with:
          version: "19.1.7"
      - name: Integration Tests
        working-directory: tests
        run: go test ./...
